docs: docs back port to 1.32 (#1604)
Back port to 1.32 version of our docs. Changes include:

* [Docs] Remove /src dir (#1018)

* docs: correct EPA doc typo of default CNI (#1052)

* docs: Add external load balancer relation to openstack how-to (#1049)

* docs: Fix ceph how-to (#1055)

* use `sudo k8s kubectl` instead of `kubectl`
* fix yaml manifests

Closes #1054

* [Docs] Add gateway how-to guide  (#1021)

* gateway how-to guide
* add sample deployment

* Docs: add to charm troubleshooting  (#1064)

* Add Cilium pod issues when deploying on MAAS

* docs: Remove see source button (#1071)

* remove see source button

remove the icon at the top of the docs of an eye to show the source code of the docs. Also removes from the footer

* fix linkcheck

* docs: How-to guide adding custom worker (#1066)

* adding worker with custom config how to

* docs(reference): Add `ip rule` priority issue to common issues (#1079)

Introduces a section to make sure priority of custom `ip rule`s are greater than `100`.

* fix broken link (#1083)

* doc: k8s-snap intermediate ca docs (#1087)

* docs:  snap landing pages rework (#1091)

* rework landing pages

alter the landing pages so that they conform with the recommended model

* docs: CAPI landing pages rework  (#1097)

* rework landing pages to display more info
* fix broken link on security page

* rework charm landing pages (#1103)

conform to standard layout and provide more info on landing pages

* chore: Document openstack health monitor behavior (#1108)

* chore: Document openstack health monitor behavior

* doc: add capi how-to for custom bootstrap config (#1122)

We're adding a how-to document, showing how to use a custom
bootstrap configuration with the Cluster API provider.

Note that this is already outlined by the config reference page:
https://documentation.ubuntu.com/canonical-kubernetes/latest/capi/reference/configs/#bootstrapconfig

* docs: how-to guide for reporting security issues (#1136)

* how to guide for reporting secuirty issues

* add mitigations to word list

* address review comments

* feat: Document how to deploy with ceph-csi against multiple ceph clusters (#1127)

* Document how to deploy with ceph-csi against multiple ceph clusters

* Address spelling errors

* Apply review comments

* docs: Ignores stigviewer.com links in linkchecker (#1144)

Recently, stigviewer.com renewed their certificate, but they are missing
their intermediate CA certificates. Because of this, creating a request
in Python results in the following error:

```
>>> import requests
>>> requests.get("https://stigviewer.com")
...
requests.exceptions.SSLError: HTTPSConnectionPool(host='stigviewer.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
```

It is a known issue that Python does not perform AIA chasing for missing
intermediate certificates on TLS connections [1].

Until this issue is resolved, we're adding https://www.stigviewer.com/.*
links in an ignore list.

[1] https://github.com/python/cpython/issues/62817

* docs: node roles (#1141)

* docs: Add charm AZ node labels reference page (#1163)

* docs: use lxd vms instead of containers (#1149)

* docs: use raw output for `yq` (#1173)

* docs: README.md update (#1114)

* update readme to include more information on the k8s snap

* Update README.md

Co-authored-by: Louise K. Schmidtgen <louise.schmidtgen@canonical.com>

* docs: Update security overview page (#1186)

* Update security overview page

* fix broken link

* fix: terraform installation doc typo (#1183)

Signed-off-by: Reza Abbasalipour <reza.abbasalipour@canonical.com>

* docs: review k8s-snap architecture diagram (#1226)

* docs: review k8sd diagram (#1230)

* docs: Update security explanation pages format (#1232)

* create security exp folder

* fix index page in navbar

* rename security file

* move security reference to a new file

* docs: review charm arch diag (#1234)

* feat: reorganize common-hardening to be a more generic security posture (#1227)

* Reorganize common-hardening to be a more generic security posture

* Fix link spelling

* Add stderr and stdout to the dictionary

* Capitlization Nit

* Apply review comments

* Remove non-howto-explanation section

* fix: juju links in docs (#1265)

Switch Juju docs to documentation.ubuntu.com

* docs: crypto usage in k8s-snap (#1243)

* update LXD privileged container info (#1276)

* docs: Fix dqlite command (#1285)

Minor typo caused this command to not be copy&pasteable

* docs: charm security reference page (#1281)

* Add charm security reference

* add reporting doc

Co-authored-by: Mateo Florido <mateoflosan@gmail.com>

* docs: Update architecture reference page (#1275)

* move arch to explanation
* refine reference page
* add charm exp page
* update diagrams
* drive by link fix

* Fix typo (#1315)

Fix small typo `boostrap` -> `bootstrap`.

* docs: add charm hardening page (#1318)

* docs: Fix markdown errors (#1334)

* docs: Update CAPI explanation page (#1330)

It was highlighted that this page was quite dense with information. This rework is to try make the info more manageable

* remove duplicate secction in reference landing page (#1416)

* docs: Adds explanation page for authentication and authorization (#1364)

* docs: Adds explanation page for authentication and authorization

Adds an explanation page for the different authentication and
authorization features present in Kubernetes.

Co-Authored-By: Niamh Hennigan <niamh.hennigan@canonical.com>

* docs: fix fmt annotations page (#1433)

* docs: Update troubleshooting with cilium tunnel port fix  (#1381)

* Update troubleshooting with cilium tunel-port fix
* Add resource reminder

* docs: Clarify creating worker join token (#1428)

* docs: Updates developer installation guide (#1437)

Adds more explanation to the developer installation guide.

* docs: Add warning about refresh-certs limitations (#1459)

---------

Co-authored-by: Mateo Florido <mateo.florido@canonical.com>
Co-authored-by: Niamh Hennigan <niamh.hennigan@canonical.com>

* docs: update starter pack framework (#1434)

* update starter pack framework

* fix spellings in docs

* fix build errors

* remove unwanted changes

* fix CI changes after rebase

* chore: update docs to address disk pressure troubleshooting (#1484)

* chore: update docs to address disk pressure troubleshooting

* fix: linting errors

* chore: address comments

* fix: custom wordlist

Signed-off-by: Reza Abbasalipour <reza.abbasalipour@canonical.com>

* docs: change layout of troubleshooting page (#1467)

* fix: change layout of troubleshooting page.

* whitespace removal to re-trigger PR build

* Add missing link

* Change layout to single page with dropdowns.

* Remove duplicate statement.

* docs: Apply user feedback (#1476)

* Apply user feedback

Cladifying items in the tutorial a new user found unclear

* remove containers reference

* update spelling

* docs: Add bridge interface workaround to troubleshooting (#1488)

* Add bridge interface workaround to troubleshooting

* Update title

* docs: snap install offline page layout rework (#1571)

* Page layout rework

This page was quite information dense which made it hard to follow. I have tried to reduce the headings, make the wording clearer and group by tabs so the user can progress through the guide smoothly. The tabs are grouped so if the user chooses side-load images, that tab will automatically be selected on the following containerd section

* minor edits

* docs: update the ports and services page for DISA PPS (#1565)

* docs: Update custom worker join how to guide (#1600)

* Update custom worker join how to

the previous example where the --name should only be used when the hostname cannot be resolved and is not the default or recommended behaviour so replacing that example and reformatting the page

* Editing the linkcheck ignore

There is a huge amount of links here for the same website that often flake and give a false positive in our tests. By only checking 3 of the links (ones starting with V-25*) we should still be altered to broken links but not have the same stability issues

* Add updates missed

* Pass woke test

* docs: update starter pack framework (#1434)

* update starter pack framework

* fix spellings in docs

* fix build errors

* remove unwanted changes

* fix CI changes after rebase

(cherry picked from commit e040282ef58d07ac53e3e46e9560a2c49df63ac2)

* Manually adding some updates

* fix md errors

* fix md errors

* fix md lint error

* remove unwanted changes

* remove unwanted changes

* fix rate limit error on linkcheck

---------

Signed-off-by: Reza Abbasalipour <reza.abbasalipour@canonical.com>
Co-authored-by: Louise K. Schmidtgen <louise.schmidtgen@canonical.com>
Co-authored-by: Homayoon Alimohammadi <homayoon.alimohammadi@canonical.com>
Co-authored-by: Benjamin Schimke <benjamin.schimke@canonical.com>
Co-authored-by: Berkay Tekin Öz <berkay.tekinoz@canonical.com>
Co-authored-by: Lucian Petrut <lpetrut@cloudbasesolutions.com>
Co-authored-by: Adam Dyess <adam.dyess@canonical.com>
Co-authored-by: Claudiu Belu <claudiu.belu@canonical.com>
Co-authored-by: eaudetcobello <etienne.audet-cobello@canonical.com>
Co-authored-by: dsloanm <dominic.sloanmurphy@canonical.com>
Co-authored-by: Reza Alipour <reza.abbasalipour@canonical.com>
Co-authored-by: Mateo Florido <mateo.florido@canonical.com>
Co-authored-by: Mateo Florido <mateoflosan@gmail.com>
Co-authored-by: Robert Gildein <gildeinrobert@gmail.com>
Co-authored-by: Alvaro Mateo <alvaromateo9@gmail.com>
Co-authored-by: Konstantinos Tsakalozos <kos.tsakalozos@canonical.com>