docs: Ignores stigviewer.com links in linkchecker (#1144)
Recently, stigviewer.com renewed their certificate, but they are missing
their intermediate CA certificates. Because of this, creating a request
in Python results in the following error:

```
>>> import requests
>>> requests.get("https://stigviewer.com")
...
requests.exceptions.SSLError: HTTPSConnectionPool(host='stigviewer.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
```

It is a known issue that Python does not perform AIA chasing for missing
intermediate certificates on TLS connections [1].

Until this issue is resolved, we're adding https://www.stigviewer.com/.*
links in an ignore list.

[1] https://github.com/python/cpython/issues/62817