test: Fixes test_cilium_e2e test (#1344) (#1417)
Currently, there are a few issues preventing the test from passing:

- instance.exec(["bash", "-c", "k8s config > ~/.kube/config"]) results
  in k8s' help being saved into ~/.kube/config, which causes the cilium
  binary to fail.
- instance.exec(["k8s", "status", "--wait-ready"]) fails with the error:

```
Error: Failed to retrieve the cluster status.

The error was: context deadline exceeded
```

- The error above is a timeout while waiting for it to become ready. The
  check is redundant, as we're already waiting for networking and dns to
  be ready.

(cherry picked from commit 6e2655db19b65ffde17eaddf762da0c9fcf5fe5d)

Co-authored-by: Claudiu Belu <claudiu.belu@canonical.com>