fix: skip snap cfg reconciliation on worker nodes
Refreshing the k8s snap on worker nodes currently fails as it
tries to reconcile the k8s configuration as part of the "configure"
hook, which is only allowed on control plane nodes.

https://github.com/canonical/k8s-snap/blob/96124bd7f1e82e96e23a4c4d11fcff86045f403c/snap/hooks/configure#L7

```
subprocess.CalledProcessError: Command '['lxc', 'shell', 'k8s-integration-42b3aa-9', '--', 'bash', '-c', 'snap refresh k8s --channel 1.32-classic/beta --classic']' returned non-zero exit status 1.

- Run configure hook of "k8s" snap if present (run hook "configure": Error: failed to update k8sd state: failed to update k8s configuration: failed after potential retry: wait check failed: failed to PUT /k8sd/cluster/config: this action is restricted on workers)
```

We'll make this command a no-op on worker nodes, logging a warning
instead of erroring out.